### ISSUE TITLE
L5.1 support

### ISSUE THREAD

**Issue by Pandahisham** [ognjenm/reservations-calendar#1]
can you bump up the support for L5.1 ?

**Comment by ognjenm** [comment]
It will be finished in 15 days +/- 5, when we port our main application (which part this calendar is) to L5

**Comment by handy-man** [comment]
Any news on a port of this into L5? Seems like something I'd like to try out/ attempt to insert into my application.

**Comment by ognjenm** [comment]
Laravel 5 support added.
