### ISSUE TITLE
Scroll to today

### ISSUE THREAD

**Issue by handy-man** [ognjenm/reservations-calendar#3]
I'm using this system to show a large number of bookings, some of them started back in lets say February.

This means that the view starts closer to the first found reservation rather than the current date, some JS to change this?

**Comment by ognjenm** [comment]
You can calculate number of days to offset, and then use javascript to scroll left.

```
    $(document).ready(function(){
        var numberOfDaysToOffset = 10;
        $( "#events-area" ).scrollLeft( 32*parseInt(numberOfDaysToOffset) );
    });
```
